# Generated by Django 3.2 on 2023-01-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_index_num',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
