# Generated by Django 3.2.16 on 2022-12-21 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_nm', models.CharField(max_length=50)),
                ('area_congest_lvl', models.CharField(max_length=50)),
                ('area_ppltn_min', models.IntegerField()),
                ('area_ppltn_max', models.IntegerField()),
                ('now', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('place_photo', models.TextField()),
                ('place_region', models.CharField(max_length=50)),
                ('place_category', models.CharField(max_length=100)),
                ('place_ncategory', models.CharField(max_length=100)),
                ('place_address', models.CharField(max_length=200)),
                ('place_street', models.CharField(blank=True, max_length=100, null=True)),
                ('place_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)])),
                ('place_tel', models.CharField(blank=True, max_length=16, null=True)),
                ('place_year10', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('place_year20', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('place_year30', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('place_year40', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('place_year50', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('place_year60', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('place_male', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('place_female', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('review_summary1', models.CharField(max_length=100)),
                ('review_summary_cnt1', models.IntegerField()),
                ('review_summary2', models.CharField(max_length=100)),
                ('review_summary_cnt2', models.IntegerField()),
                ('review_summary3', models.CharField(max_length=100)),
                ('review_summary_cnt3', models.IntegerField()),
                ('review1', models.TextField()),
                ('review2', models.TextField()),
                ('review3', models.TextField()),
                ('review4', models.TextField()),
                ('review5', models.TextField()),
                ('review6', models.TextField()),
                ('review7', models.TextField()),
                ('review8', models.TextField()),
                ('review9', models.TextField()),
                ('review10', models.TextField()),
                ('review_blog_count', models.IntegerField()),
                ('review_count', models.IntegerField()),
                ('review_keywords', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
