# Generated by Django 3.2 on 2022-12-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nickname', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.png', upload_to='profile/')),
                ('age', models.CharField(choices=[('age_10', '10대'), ('age_20', '20대'), ('age_30', '30대'), ('age_40', '40대'), ('age_50', '50대'), ('age_60', '60대'), ('age_none', '선택안함')], default='age_none', max_length=30)),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성'), ('gender_none', '선택안함')], default='gender_none', max_length=30)),
                ('mbti', models.CharField(choices=[('mbti_istj', 'ISTJ'), ('mbti_istp', 'ISTP'), ('mbti_isfj', 'ISFJ'), ('mbti_isfp', 'ISFP'), ('mbti_intj', 'INTJ'), ('mbti_intp', 'INTP'), ('mbti_infj', 'INFJ'), ('mbti_infp', 'INFP'), ('mbti_estj', 'ESTJ'), ('mbti_estp', 'ESTP'), ('mbti_esfj', 'ESFJ'), ('mbti_esfp', 'ESFP'), ('mbti_entj', 'ENTJ'), ('mbti_entp', 'ENTP'), ('mbti_enfj', 'ENFJ'), ('mbti_enfp', 'ENFP'), ('mbti_none', '선택안함')], default='mbti_none', max_length=30)),
                ('restaurant_korea', models.BooleanField(default=False)),
                ('restaurant_west', models.BooleanField(default=False)),
                ('restaurant_china', models.BooleanField(default=False)),
                ('restaurant_japan', models.BooleanField(default=False)),
                ('restaurant_fast', models.BooleanField(default=False)),
                ('restaurant_bunsik', models.BooleanField(default=False)),
                ('cafe_cafe', models.BooleanField(default=False)),
                ('cafe_dessert', models.BooleanField(default=False)),
                ('cafe_bakery', models.BooleanField(default=False)),
                ('leisure_gallery', models.BooleanField(default=False)),
                ('leisure_craft', models.BooleanField(default=False)),
                ('leisure_popup', models.BooleanField(default=False)),
                ('leisure_theater', models.BooleanField(default=False)),
                ('leisure_book', models.BooleanField(default=False)),
                ('leisure_department', models.BooleanField(default=False)),
                ('walking_park', models.BooleanField(default=False)),
                ('walking_market', models.BooleanField(default=False)),
                ('walking_street', models.BooleanField(default=False)),
            ],
        ),
    ]
