# Generated by Django 3.2 on 2022-12-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
