# Generated by Django 3.2 on 2022-12-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('gender_male', '남성'), ('gender_female', '여성'), ('gender_none', '선택안함')], default='gender_none', max_length=30),
        ),
    ]
