# Generated by Django 3.2 on 2022-12-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221217_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(choices=[('age_10', '10대'), ('age_20', '20대'), ('age_30', '30대'), ('age_40', '40대'), ('age_50', '50대'), ('age_60', '60대')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('mbti_istj', 'ISTJ'), ('mbti_istp', 'ISTP'), ('mbti_isfj', 'ISFJ'), ('mbti_isfp', 'ISFP'), ('mbti_intj', 'INTJ'), ('mbti_intp', 'INTP'), ('mbti_infj', 'INFJ'), ('mbti_infp', 'INFP'), ('mbti_estj', 'ESTJ'), ('mbti_estp', 'ESTP'), ('mbti_esfj', 'ESFJ'), ('mbti_esfp', 'ESFP'), ('mbti_entj', 'ENTJ'), ('mbti_entp', 'ENTP'), ('mbti_enfj', 'ENFJ'), ('mbti_enfp', 'ENFP')], default='none', max_length=30),
        ),
    ]
